import mongoose from 'mongoose';

const userSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  googleId: { type: String, required: true },
  role: { type: String, required: true, enum: ['admin', 'patient', 'clinic', 'doctor', 'laboratory', 'hospital'] },
  isVerified: { type: Boolean, default: true },
  verificationStatus: { type: String, enum: ['pending', 'approved', 'rejected'], default: 'approved' },
  onboardingComplete: { type: Boolean, default: false },
  profile: {
    fullName: String,
    picture: String,
    dob: String,
    gender: String,
    bloodGroup: String,
    preferredLanguage: String,
    address: String,
    contactMethods: [String],
    emergencyContactName: String,
    emergencyRelationship: String,
    emergencyPhone: String,
    allergies: [String],
    chronicConditions: [String],
    currentMedications: String,
    dietaryPreferences: String,
    lifestyleHabits: String,
    familyMedicalHistory: [String],
    insuranceProvider: String,
    policyNumber: String,
    consentGiven: { type: Boolean, default: false },
    familyMembers: [Object],
    clinicProfile: {
      clinicName: String,
      logoUrl: String,
      specialityType: String,
      establishmentYear: String,
      registrationNumber: String,
      ownerName: String,
      taxId: String,
      proofDocumentName: String,
      proofDocumentData: String,
      address: String,
      mapsLink: String,
      phoneNumber: String,
      emergencyPhone: String,
      workingDays: [String],
      morningHours: String,
      eveningHours: String,
      consultationTime: String,
      consultationFee: String,
    },
    labProfile: {
      labName: String,
      logoUrl: String,
      labType: String,
      operatingModel: String,
      registrationNumber: String,
      chiefDoctorName: String,
      licenseNumber: String,
      certificateName: String,
      certificateData: String,
      businessEmail: String,
      mapsLink: String,
      bankAccountNumber: String,
      bankAccountName: String,
      bankCode: String,
      chequeName: String,
      chequeData: String,
      workingDays: [String],
      openingTime: String,
      closingTime: String,
      weeklyOff: [String],
      homeCollection: Boolean,
      availableTests: [String],
      pricingSheet: String,
    },
    hospitalProfile: {
      hospitalName: String,
      logoUrl: String,
      hospitalType: String,
      registrationNumber: String,
      licenseNumber: String,
      licenseName: String,
      licenseData: String,
      totalBeds: String,
      icuBeds: String,
      ambulanceAvailable: Boolean,
      address: String,
      mapsLink: String,
      emergencyLandline: String,
      bankAccountNumber: String,
      bankAccountName: String,
      bankIFSC: String,
      users: [Object],
    },
  },
  createdAt: { type: Date, default: Date.now },
});

const User = mongoose.models.User || mongoose.model('User', userSchema);
export default User;
